Feat: Display Recommended Workflows in VSCode Plugin
devchat-ai/devchat-vscode pull request #469
Opened 2024-03-26 08:20 UTC by yangbobo2021

This pull request integrates the display of recommended workflows within the devchat VSCode plugin, addressing the user experience enhancement detailed in issue #305.

The following changes have been implemented:

1. Dependencies have been updated, adding @iarna/toml to `package.json` for the configuration file parsing.

2. The `fs` and `os` modules along with promisify have been imported to enable asynchronous file reading.

3. An asynchronous method has been created to load and parse the recommended workflows configuration file.

4. The `CommandEntry` interface has been extended, and the command logic has been adjusted to incorporate workflow recommendations.

This PR closes devchat-ai/devchat#305.

2024-03-26 08:27 UTC, yangbobo2021 commented
/review

2024-03-26 08:33 UTC, yangbobo2021 commented
/review

2024-03-26 11:20 UTC, pplam requested changes

2024-03-26 11:20 UTC, pplam commented on src/toolwrapper/devchat.ts
> +				recommend: cmd.recommend ?? -1,
直接在这里找到它在 recommendCommands 中的 index 加上就可以了，不用再去迭代一遍 recommendCommands

2024-03-27 00:41 UTC, yangbobo2021 commented on src/toolwrapper/devchat.ts
> +				recommend: cmd.recommend ?? -1,
放这里也是可以的，这样代码更加简洁。没有放这里的主要原因是，希望将逻辑分为两个更容易理解的步骤，步骤1，加载所有命令列表，步骤2，处理过滤命令列表序号。多几行代码，理解上会更简单一些，所以选择了这种方式。

2024-03-27 00:56 UTC, yangbobo2021 commented on src/toolwrapper/devchat.ts
> +				recommend: cmd.recommend ?? -1,
再多考虑了下，好像将步骤修改为这样也是合适的，步骤1，加载原始命令列表；步骤2，设置过滤排序值。按这个步骤设计，那确实应该把代码进行合并处理。

2024-03-27 01:26 UTC, pplam approved these changes

2024-03-27 02:26 UTC, merged

2024-03-27 03:25 UTC, yangbobo2021 commented
/analyze

2024-03-27 03:27 UTC, yangbobo2021 commented
/analyze